PayrexxIntegrationService:
  Db:
    LogsConnString:
      settings-key: PayrexxIntegrationService-LogsConnString
      types:
        - AzureTableStorage
  PayrexxApiBaseUrl:
    settings-key: PayrexxIntegrationService-PayrexxApiBaseUrl
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
CustomerProfileServiceClient:
    ServiceUrl:
        settings-key: CustomerProfileServiceUrl
